config {
        type: "operations",
        tags: ["CLEANER"],
        dependencies: ["bi_pericia_licenca_original_2"]
}

DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPLO_etp01_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPLO_etp02_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPLO_etp03_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPLO_etp04_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPLO_etp05_vw_tmp`;
