config {
    type: "view",
    tags: ["BPLO"],
    name: "BPLO_etp04_vw_tmp",
    description: ""
}

WITH VALOR_BRUTO AS (
    SELECT DISTINCT
        F.VALOR,
        F.NUMFUNC,
        F.NUMVINC,
        F.MES_ANO_FOLHA
    FROM `rj-smfp.recursos_humanos_ergon.ficha_financeira` F
    JOIN `rj-smfp.recursos_humanos_ergon_staging.folha_empresa` FE ON 
        (
            CAST(F.mes_ano_folha AS STRING) = FE.mes_ano
            AND CAST(F.num_folha AS STRING) = FE.numero
            AND F.emp_codigo = FE.emp_codigo
            -- TODO: ALTERAR A REFERENCIA DA TABELA PARA APONTAR PARA FORA DO STAGING
        )
    WHERE
        CAST(MES_ANO_DIREITO AS DATE) = MES_ANO_FOLHA 
        AND F.RUBRICA = '996' AND FE.TIPO_FOLHA IN ('NORMAL')
        AND FE.DATA_CONSOL IS NOT NULL  
), 
CTE6 AS (
    select 
        A.*, 
        B.VALOR, 
        DATE_TRUNC(A.DTINI, MONTH) as dtinicio, 
        B.MES_ANO_FOLHA
from ${ref("BPLO_etp03_vw_tmp")} A 
    left join VALOR_BRUTO B ON A.NUMFUNC = B.NUMFUNC and A.NUMVINC = B.NUMVINC and B.MES_ANO_FOLHA = DATE_TRUNC(A.DTINI, MONTH) 
)
, CTE7 AS (
    select 
        matricula, IDENTIFICADOR_LICENCA, count(IDENTIFICADOR_LICENCA) as idas_pericia_mesma_licenca
    from CTE6
    group by matricula, IDENTIFICADOR_LICENCA
)

SELECT 
        A.*, B.idas_pericia_mesma_licenca
FROM CTE6 A
    LEFT JOIN CTE7 B ON A.matricula = B.matricula and A.IDENTIFICADOR_LICENCA = B.IDENTIFICADOR_LICENCA