config {
    type: "view",
    name: "BPRA_etp04_vw_tmp",
    description: ""
}

select distinct 
   A.*,
   C.nome
from ${ref("BPRA_etp03_vw_tmp")}  A
   LEFT JOIN `rj-smfp.recursos_humanos_ergon.vinculo` V
      ON A.MATRICULA = V.id_matricula_vinculo
    LEFT JOIN `rj-smfp.recursos_humanos_ergon.provimento` P ON 
        (
            V.id_funcionario = P.id_funcionario
            AND V.id_vinculo = P.id_vinculo
            AND P.empresa_vinculo = V.id_empresa
        )
   LEFT JOIN `rj-smfp.recursos_humanos_ergon.cargo` C ON C.id_cargo = P.id_cargo