config {
    type: "view",
    name: "BPRA_etp04_vw_tmp",
    description: ""
}

select distinct 
   A.*,
   C.nome
from ${ref("BPRA_etp03_vw_tmp")}  A
   LEFT JOIN `rj-smfp.recursos_humanos_ergon_staging.vinculo` V
      ON A.MATRICULA = V.matric
   LEFT JOIN `rj-smfp.recursos_humanos_ergon_staging.provimento` P
      ON  V.NUMFUNC = P.NUMFUNC
      AND V.NUMERO = P.NUMVINC
      AND P.EMP_CODIGO = V.EMP_CODIGO
   LEFT JOIN `rj-smfp.recursos_humanos_ergon_staging.cargo` C
      ON C.CARGO = P.CARGO