config {
    type: "view",
    name: "BPRA_etp05_vw_tmp",
    description: ""
}

select distinct
        A.NUMFUNC,
        V.NUMVINC,
        A.MATRICULA,
        P.dtini,
        C.cargo_padronizado,
        C.categoria,
        C.subcategoria,
        C.CARGO_PRIVATIVOS,
        C.CARGO_PRIVATIVOS_SUB
FROM ${ref("BPRA_etp04_vw_tmp")}  A
    LEFT JOIN (SELECT id_funcionario as numfunc, id_vinculo as numvinc, id_matricula_vinculo as matric, id_empresa as emp_codigo FROM `rj-smfp.recursos_humanos_ergon.vinculo` ) V ON
        cast(A.NUMFUNC as string) = cast(V.numfunc as string)
        AND cast(A.MATRICULA as string) = cast(V.matric as string)
    LEFT JOIN (select id_funcionario, id_vinculo, empresa_vinculo, id_cargo, max(data_inicio) as dtini from `rj-smfp.recursos_humanos_ergon.provimento` group by 1,2,3,4) P ON
            (
                V.numfunc = P.id_funcionario
                AND V.numvinc = P.id_vinculo
                AND P.empresa_vinculo = V.emp_codigo
            )
        --AND cast(p.dtini as date) >= cast(pericia_geral.DTINI as date)
    LEFT JOIN `rj-smfp-dev.dashboard_ergon_folha_subggc.cargos_depara` C
        ON C.CARGO = P.id_cargo
where CARGO_PADRONIZADO is not null