config {
    type: "view",
    tags: ["BPLC"],
    name: "BPLC_etp03_vw_tmp",
    description: ""
}


WITH AUX1 as (
    select
        NUMFUNC
        , MAX(IDENTIFICADOR_LICENCA) AS MAXIDLIC
    FROM ${ref("BPLC_etp02_vw_tmp")}
    GROUP BY 1
)

, AUX2 as (
    select NUMFUNC
        , IDENTIFICADOR_LICENCA
        , SUM(DIAS) AS DIAS_TOTAL_LICENCA
    FROM ${ref("BPLC_etp02_vw_tmp")}
    GROUP BY 1,2
)

select A.*
     , CASE
            WHEN B.MAXIDLIC =1 THEN '1 licença'
            WHEN B.MAXIDLIC =2 THEN '2 licenças'
            WHEN B.MAXIDLIC =3 THEN '3 licenças'
            WHEN B.MAXIDLIC =4 THEN '4 licenças'
            WHEN B.MAXIDLIC =5 THEN '5 licenças'
            WHEN B.MAXIDLIC >=6 AND B.MAXIDLIC <=10 THEN '6 a 10 licenças'
            WHEN B.MAXIDLIC >10 THEN 'Mais de 10 licenças'
       END DESCMAXIDLIC
     , CASE
            WHEN A.IDAS_PERICIA_MESMA_LICENCA =1 THEN '1 atendimento'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA =2 THEN '2 atendimentos'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA =3 THEN '3 atendimentos'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA =4 THEN '4 atendimentos'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA =5 THEN '5 atendimentos'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA >=6 AND A.IDAS_PERICIA_MESMA_LICENCA <=10 THEN '6 a 10 atendimentos'
            WHEN A.IDAS_PERICIA_MESMA_LICENCA >10 THEN 'Mais de 10 atendimentos'
       END IDAS_AGRUP
     , CASE
	       WHEN C.DIAS_TOTAL_LICENCA<=15 THEN 'Até 15 dias'
            WHEN C.DIAS_TOTAL_LICENCA>15 AND C.DIAS_TOTAL_LICENCA<=30 THEN 'De 16 a 30 dias'
            WHEN C.DIAS_TOTAL_LICENCA>30 AND C.DIAS_TOTAL_LICENCA<=60 THEN 'De 31 a 60 dias'
            WHEN C.DIAS_TOTAL_LICENCA>60 AND C.DIAS_TOTAL_LICENCA<=180 THEN 'De 61 a 180 dias'
            WHEN C.DIAS_TOTAL_LICENCA>180 AND C.DIAS_TOTAL_LICENCA<720 THEN 'Entre 181 e 720 dias'
            WHEN C.DIAS_TOTAL_LICENCA>=720 THEN 'Mais de 720 dias'
       END DIAS_POR_FAIXA_TEMPO
from ${ref("BPLC_etp02_vw_tmp")} A
LEFT JOIN AUX1 B ON A.NUMFUNC = B.NUMFUNC
LEFT JOIN AUX2 C ON A.NUMFUNC = C.NUMFUNC AND A.IDENTIFICADOR_LICENCA = C.IDENTIFICADOR_LICENCA