config {
    type: "view",
    tags: ["BPAO"],
    name: "BPAO_etp02_vw_tmp",
    description: ""
}

SELECT 
    DISTINCT
    VW.chave AS CHAVEPRONT --ERGON.PRONTUARIO --ATENCAO! essa variavel faz duplicar
    , J.ID_JUNTA
    , P.NUMFUNC
    , VW.MATRICULA
    , VW.NOMESERVIDOR
    , VW.DTATEND --ERGON.PRONTUARIO --ATENCAO! essa variavel faz duplicar
    , VW.DTCONCLUSAO AS DTCONCLUSAO_JUNTA --ERGON.PRONTUARIO --ATENCAO! essa variavel faz duplicar
    , J.DTCONCLUSAO AS DTCONCLUSAO_HOMOLOGACAO
    , P.cod_cid1
    , P.COD_CID2
    , P.COD_CID3
    , E.GRUPO2EXAME AS TIPO_ATENDIMENTO --bi_pericia_geral=GRUPO2
    , VW.GRUPOEXAME AS GRUPO_PERICIA_CODIGO --ERGON.EXAMES e ERGON.ERG_PM_GRUPOEXAME (igual nas duas)
    , VW.NOMEGRUPO AS GRUPO_PERICIA_DESC --ERGON.ERG_PM_GRUPOEXAME variavel NOME (eh o que chamamos de GRUPO_PERICIA no codigo de licenca)
    , VW.SIGLAEXAME AS SIGLA --ERGON.EXAME igual a SIGLA da ERGON.PRONTUARIO e igual a SIGLAEXAME da ERGON.DECISAO
    , VW.SIGLAEXAME2 AS SIGLA_DESC --ERGON.EXAME variavel chama NOME e eh a descricao da SIGLA (ERGON.PRONTUARIO, ERGON.DECISAO e ERGON.EXAME)
    , VW.DECISAO AS DECISAO_PERITOJUNTA_CODIGO --ERGON.PRONTUARIO (eh um codigo cuja descricao se encontra na tabela ERGON.DECISAO, nas variaveis SIGLA e DESCRICAO)
    , VW.SIGLA_DECISAO AS DECISAO_PERITOJUNTA --ERGON.DECISAO chamamos de RESULTADO no codigo de licenca
    , VW.SIGLA_DECISAO2 AS DECISAO_PERITOJUNTA_DESC --ERGON.DECISAO descricao da SIGLA_DECISAO
    , RJ.DECISAO AS DECISAO_PHOMOLOGADOR_CODIGO
    , D.SIGLA AS DECISAO_PHOMOLOGADOR_RESULT
    , D.DESCRICAO AS DECISAO_PHOMOLOGADOR_DESC
    , J.JUSTIFICATIVA AS PHOMOLOGADOR_JUSTIFICATIVA
    , RJ.CRM AS PERITO_HOMOLOGADOR_CRM --se for necessario tem tambem ID_RESULTJUNTA
    , M.NOME AS PERITO_HOMOLOGADOR_NOME
    , V.data_posse AS DTPOSSE
    , V.data_vacancia AS DTVAC
    , V.id_empresa AS EMP_CODIGO
    , F.SEXO
    , TRUNC(DATE_DIFF(CAST(VW.dtatend AS DATE), F.data_nascimento, MONTH) / 12) AS IDADE
    , PR.SIGLA_SEC AS ORGAO
    , PR.DTINI_LOTACAO
    , PR.DTFIM_LOTACAO
    , CASE 
            WHEN P.cod_cid1 >= 'A00' AND P.cod_cid1 <= 'B99.9999'   THEN 'Doenças infecciosas e parasitárias'
            WHEN P.cod_cid1 >= 'C00' AND P.cod_cid1 <= 'D48.9999'   THEN 'Neoplasias (tumores)'
            WHEN P.cod_cid1 >= 'D50' AND P.cod_cid1 <= 'D89.9999'   THEN 'Doenças do sangue e do sistema imunológico'
            WHEN P.cod_cid1 >= 'E00' AND P.cod_cid1 <= 'E90.9999'   THEN 'Doenças endócrinas nutricionais e metabólicas'
            WHEN P.cod_cid1 >= 'F00' AND P.cod_cid1 <= 'F99.9999'   THEN 'Transtornos mentais e comportamentais'
            WHEN P.cod_cid1 >= 'G00' AND P.cod_cid1 <= 'G99.9999'   THEN 'Doenças do sistema nervoso'
            WHEN P.cod_cid1 >= 'H00' AND P.cod_cid1 <= 'H59.9999'   THEN 'Doenças do olho e anexos'
            WHEN P.cod_cid1 >= 'H60' AND P.cod_cid1 <= 'H95.9999'   THEN 'Doenças do ouvido'
            WHEN P.cod_cid1 >= 'I00' AND P.cod_cid1 <= 'I99.9999'   THEN 'Doenças do aparelho circulatório'
            WHEN P.cod_cid1 >= 'J00' AND P.cod_cid1 <= 'J99.9999'   THEN 'Doenças do aparelho respiratório'
            WHEN P.cod_cid1 >= 'K00' AND P.cod_cid1 <= 'K93.9999'   THEN 'Doenças do aparelho digestivo'
            WHEN P.cod_cid1 >= 'L00' AND P.cod_cid1 <= 'L99.9999'   THEN 'Doenças da pele e do tecido subcutâneo'
            WHEN P.cod_cid1 >= 'M00' AND P.cod_cid1 <= 'M99.9999'   THEN 'Doenças nos ossos, músculos e tecidos conectivos'
            WHEN P.cod_cid1 >= 'N00' AND P.cod_cid1 <= 'N99.9999'   THEN 'Doenças do aparelho geniturinário'
            WHEN P.cod_cid1 >= 'O00' AND P.cod_cid1 <= 'O99.9999'   THEN 'Gravidez parto e puerpério'
            WHEN P.cod_cid1 >= 'P00' AND P.cod_cid1 <= 'P96.9999'   THEN 'Condições perinatais e neonatais'
            WHEN P.cod_cid1 >= 'Q00' AND P.cod_cid1 <= 'Q99.9999'   THEN 'Anomalias congênitas e genéticas'
            WHEN P.cod_cid1 >= 'R00' AND P.cod_cid1 <= 'R99.9999'   THEN 'Sinais e sintomas não específicos'
            WHEN P.cod_cid1 >= 'S00' AND P.cod_cid1 <= 'T98.9999'   THEN 'Traumas, envenenamento e ações externas'
            WHEN P.cod_cid1 >= 'V01' AND P.cod_cid1 <= 'Y98.9999'   THEN 'Fatores externos de risco para a saúde'
            WHEN P.cod_cid1 >= 'Z00' AND P.cod_cid1 <= 'Z99.9999'   THEN 'Atendimentos em serviços de saúde'
            WHEN P.cod_cid1 >= 'U04' AND P.cod_cid1 <= 'U99.9999'   THEN 'Códigos para propósitos especiais'
            ELSE 'Sem informação'
        END AS GRUPAMENTO_CID
    , M.CRM
FROM `rj-smfp.recursos_humanos_ergon_pericia_medica.tpmrj_pm_vwtpconclper` VW
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.prontuario` P ON VW.chave = P.chave
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.erg_pm_pront_med` PM ON P.chave = PM.chavepront
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.medicos` M ON PM.crm = M.crm
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.exames` E ON P.sigla = E.sigla
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.erg_pm_grupoexame` G ON REGEXP_REPLACE(E.grupoexame, r'\.\d+', '') = G.grupoexame
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.tpmrj_pm_periciasjunta` PJ ON P.CHAVE = PJ.chavepront
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.tpmrj_pm_juntas` J ON PJ.id_junta = J.id_junta
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.tpmrj_pm_resultjunta` RJ ON J.id_junta = RJ.id_junta
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.medicos` M1 ON RJ.crm = M1.crm
    LEFT JOIN `rj-smfp.recursos_humanos_ergon_pericia_medica.erg_pm_decisao` D ON RJ.decisao = D.decisao
    LEFT JOIN `rj-smfp.recursos_humanos_ergon.vinculo` V ON V.id_matricula_vinculo = VW.matricula
    LEFT JOIN `rj-smfp.recursos_humanos_ergon.funcionario` F ON F.id_vinculo = V.id_funcionario
    LEFT JOIN ${ref("BPAO_etp01_vw_tmp")} PR
        ON VW.matricula = PR.MATRIC
        AND (CAST(VW.dtatend AS DATE) >= PR.DTINI_LOTACAO and CAST(VW.dtatend AS DATE) <= PR.DTFIM_LOTACAO )
WHERE
    VW.DTATEND >= '2017-01-01'
    and VW.SIGLAEXAME2 LIKE '%APOS%'
    and VW.NOMEGRUPO LIKE '%APOS%'
ORDER BY P.NUMFUNC
