config {
  type: "declaration",
  schema: "dataform_sources"
}

-- @name Modelo da Tabela Source com Filtro de Partições após 2023
-- @description Modelo que filtra apenas as partições após 2023 na tabela `rj-smfp.recursos_humanos_ergon.fita_banco`.
WITH filtro_por_particao AS (
  SELECT *
  FROM `rj-smfp.recursos_humanos_ergon.fita_banco`
  WHERE data_particao >= '2023-08-01'
)
 
-- Defina a estrutura da tabela source com base no filtro de partição
SELECT
  *
FROM
  filtro_por_particao;