config {
    
    type: "table"
    , name: "aux_SES_setor_n01"
    , description: "Tabela com todos os SETORES onde os funcionários podem ser lotados"
    , columns: {
        id_aux: "Numeração inserida para identificar cada registro unicamente, com o intuito de auxiliar na resolução de inconsistências"
        , setor: "Código, dado pelo SICI, do setor de lotação"
        , codigo_secretaria: "Originário do campo flex_campo_05, cuja função é registrar o código da secretaria à qual o setor pertence. Funciona como um autorrelacionamento"
        , sigla: "Sigla do setor. Ex.: FP/SUBGGC. Originário do campo flex_campo_01, cuja função é registrar a sigla do setor"
        , emp_codigo: "Código da empresa a qual o setor pertence"
        , nome: "Nome do setor, possivelmente abreviado pelo tamanho do atributo. Originário do campo nomesetor"
        , inicio: "Registra a data de início do setor. Originário do campo dataini"
        , fim: "Registra a data de encerramento do setor. Originário do campo datafim"
        , fim_aux: "Campo calculado para substituir o NULL dos setores que ainda estão ativos por uma data no futuro, com o objetivo de viabilizar a verificação de intervalos de início e fim"
        , ordem_desc: "Campo calculado que facilita a ordenação dos setores em relação ao período de existência. Ex.: 1 indica o registro mais recente do setor"
    }
}

    SELECT
        DISTINCT
        ROW_NUMBER() over () AS id_aux
        , TRIM(stor.setor) AS setor
        , TRIM(stor.flex_campo_05) AS codigo_secretaria
        , TRIM(stor.flex_campo_01) AS sigla
        , TRIM(stor.emp_codigo) as emp_codigo
        , TRIM(UPPER(stor.nomesetor)) AS nome
        , PARSE_DATE('%Y-%m-%d',stor.DATAINI) as inicio
        , COALESCE(PARSE_DATE('%Y-%m-%d', stor.datafim), DATE('9999-01-01')) AS fim_aux
        , stor.datafim AS fim
        , ROW_NUMBER() OVER (PARTITION BY stor.setor, stor.emp_codigo ORDER BY stor.dataini DESC) AS ordem_desc
    FROM 
        `rj-smfp.recursos_humanos_ergon_staging.setor` stor