config {
    type: "table"
    , name: "aux_SES_secretaria_n01"
    , description: "Tabela autorelacionada no campo setor e flex_campo_05. Aqui ela representa a entidade SECRETARIA. São considerados registros que atuam como secretarias aqueles cujo valor do campo setor tem correspondência em outro registro no campo flex_campo_05."
    , columns: {
        setor: "O setor"
        , codigo: "Originário do campo flex_campo_05, cuja função é registrar o código da secretaria. Neste caso, como o registro representa uma secretaria, setor = codigo"
        , sigla: "Sigla da secretaria. Originário do campo flex_campo_01, cuja função é registrar a sigla do setor, neste caso, uma secretaria"
        , emp_codigo: "Código da empresa a qual a secretaria pertence"
        , nome: "Nome da secretaria"
        , inicio: "Registra a data de início da secretaria. Originário do campo dataini"
        , fim: "Registra a data de encerramento da secretaria. Originário do campo datafim"
        , calculada: "Valor padrão FALSE. No processo de reconhecimento dos registros que atuam como secretarias, os registros inseridos posteriormente são marcados como TRUE, calculados"
    }
}
-- São considerados registros que atuam como secretarias aqueles cujo valor do campo setor tem correspondência em outro registro no campo flex_campo_05.
SELECT
    DISTINCT
    TRIM(stor.setor) as setor
    , TRIM(stor.flex_campo_05) AS codigo
    , COALESCE(TRIM(stor.flex_campo_01), LAG(TRIM(stor.flex_campo_01), 1) OVER (PARTITION BY stor.setor, stor.emp_codigo ORDER BY stor.DATAINI)) AS sigla
    , TRIM(stor.emp_codigo) as emp_codigo
    , TRIM(UPPER(stor.nomesetor)) AS nome
    , PARSE_DATE('%Y-%m-%d', stor.dataini) AS inicio
    , COALESCE(PARSE_DATE('%Y-%m-%d', stor.datafim), DATE('9999-01-01')) AS fim_aux
    , stor.datafim AS fim
    , FALSE AS calculada
FROM 
    `rj-smfp.recursos_humanos_ergon_staging.setor` stor
    JOIN (select distinct flex_campo_05 from`rj-smfp.recursos_humanos_ergon_staging.setor`) dsec ON
        TRIM(stor.setor) = TRIM(dsec.flex_campo_05)



