config {
    type: "view",
    tags: ["BPRV"],
    name: "BPRV_etp03_vw_tmp",
    description: ""
}

WITH MAXIMO AS (
    SELECT NUMFUNC,
           MAX(OCORRENCIAS_READAPTACAO) AS QTD_MAX_READAP
    FROM ${ref("BPRV_etp02_vw_tmp")}
    GROUP BY 1
)

SELECT A.*,
       B.QTD_MAX_READAP
FROM ${ref("BPRV_etp02_vw_tmp")} A
  LEFT JOIN MAXIMO B
  ON A.NUMFUNC = B.NUMFUNC
ORDER BY A.NUMFUNC, A.OCORRENCIAS_READAPTACAO, A.DTINI_VANTAGEM