config {
        type: "operations",
        tags: ["CLEANER"],
        dependencies: ["bi_pericia_readaptacao_vantagens_2"]
}

DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRV_etp01_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRV_etp02_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRV_etp03_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRV_etp04_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRV_etp05_vw_tmp`;
