config {
        type: "operations",
        tags: ["CLEANER"],
        dependencies: ["bi_pericia_readaptacao_original_2"]
}

DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRO_etp01_readaptacao_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRO_etp02_readaptacao_vw_tmp`;
DROP VIEW IF EXISTS `rj-smfp-dev.dashboard_ergon_pericia_medica_subggc.BPRO_etp03_readaptacao_vw_tmp`;
