-- Defina um modelo SQLX para a fonte filtrada.
config {
  type:"table",
  name:"fita_banco_filtered",
  schema:"dashboard_test",
  description:"Fonte filtrada para o ano de 2023."
}

-- Consulta SQLX que filtra os dados para o ano de 2023 usando a coluna `data_particao`.
SELECT
    data_folha,
    EXTRACT(YEAR FROM data_folha) AS ano,
    EXTRACT(MONTH FROM data_folha) AS mes,
    id_funcao,
    nome_fita_banco,
    valor_liquido,
    regime_juridico,
FROM `rj-smfp.recursos_humanos_ergon.fita_banco`
WHERE data_particao > '2023-01-01'