config {
    type: "view",
    tags: ["BPAP"],
    name: "BPAP_etp04_vw_tmp",
    description: ""
}


SELECT
  DISTINCT
  A.*,
  C.CARGO_PADRONIZADO,
  C.CARGO_PRIVATIVOS
FROM ${ref("BPAP_etp03_vw_tmp")} A
  LEFT JOIN `rj-smfp.recursos_humanos_ergon.vinculo` V
    ON A.MATRICULA = V.id_matricula_vinculo
  LEFT JOIN (select id_funcionario, id_vinculo, empresa_vinculo, id_cargo, max(data_inicio) as dtini
             from `rj-smfp.recursos_humanos_ergon.provimento`
             group by 1,2,3,4) P
    ON V.id_funcionario = P.id_funcionario
    AND V.id_vinculo = P.id_vinculo
    AND P.empresa_vinculo = V.id_empresa
  LEFT JOIN `rj-smfp-dev.dashboard_ergon_folha_subggc.cargos_depara` C
    ON C.CARGO = P.id_cargo