config {
    type: "table",
    name: "BPT_etp03_joincargo_tmp",
    description: ""
}

SELECT
  A.CHAVEPRONT
  , A.ID_JUNTA
  , A.NUMFUNC
  , A.MATRICULA
  , A.TIPO_ATENDIMENTO
  , A.GRUPO_PERICIA_DESC
  , A.SIGLA
  , A.DECISAO_PERITO
  , A.DECISAO_PERITO_DESC
  , A.DECISAO_PHOMOLOGADOR_RESULT
  , A.DECISAO_PHOMOLOGADOR_DESC
  , A.PERITO_HOMOLOGADOR_CRM
  , A.PERITO_HOMOLOGADOR_NOME
  , A.EMP_CODIGO
  , A.SEXO
  , A.ORGAO
  , A.GRUPAMENTO_CID
  , A.CRM
  , A.NOME_PERITO
  , A.JORNADA_PERITO
  , A.NOME_FG
  , DTATEND
  ,  CASE
        WHEN safe_cast(A.IDADE AS INT64) <= 25 THEN 'Até 25 anos'
        WHEN safe_cast(A.IDADE AS INT64) BETWEEN 26 AND 40 THEN 'De 26 a 40 anos'
        WHEN safe_cast(A.IDADE AS INT64) BETWEEN 40 AND 55 THEN 'De 41 a 55 anos'
        WHEN safe_cast(A.IDADE AS INT64) BETWEEN 55 AND 70 THEN 'De 56 a 70 anos'
        WHEN safe_cast(A.IDADE AS INT64) > 70 THEN 'Mais de 70 anos'
        ELSE 'Não informado'
    END AS IDADE
    , C.nome as CARGO_SERVIDOR
    , C.CARGO_PADRONIZADO
    , C.CARGO_PRIVATIVOS
FROM ${ref("BPT_etp02_info_vw_tmp")} AS A
  LEFT JOIN `rj-smfp.recursos_humanos_ergon_staging.vinculo` AS V ON A.MATRICULA = V.matric
  LEFT JOIN (
              SELECT numfunc, NUMVINC, EMP_CODIGO, CARGO, max(dtini) as dtini
              FROM `rj-smfp.recursos_humanos_ergon_staging.provimento`
              GROUP BY 1,2,3,4
            ) AS P ON
    (
      cast(V.numfunc AS string) = cast(P.NUMFUNC AS string)   
      AND cast(V.numero AS string) = cast(P.NUMVINC  AS string) 
    )
  LEFT JOIN `rj-smfp-dev.dashboard_ergon_folha_subggc.cargos_depara`C ON C.CARGO = P.CARGO










