config {
    
    type: "table",
    name: "dTb_Empresa_setor_inativos_pensionistas",
    schema: "dashboard_ergon_folha_subggc",
    description: "Esta tabela traz as informacoes de codigo e nome das empresas da PREVI-RIO"

}
select 
    distinct 
     id_empresa
    ,id_secretaria
    ,id_setor
    ,sigla
  from
    `rj-smfp.recursos_humanos_ergon.setor`
  where
     id_empresa in ('2', '4') 
  order by 
    id_empresa