config {
    type: "table"
    , tags: ["EXEC"]
    , name: "aux_setor_secretaria_n02"
    , description: "Tabela que junta todos e setores e suas respectivas secretarias observando o intervalo de tempo de suas existencias"
    , columns: {
        id_aux: "Numeração inserida para identificar cada registro unicamente, com o intuito de auxiliar na resolução de inconsistências"
        , sec_codigo: "Código da secretaria, originário da tabela aux_SES_setor_n01"
        , sec_sigla: "Código da secretaria, originário da tabela aux_SES_secretaria_n01"
        , setor: "Código do setor, originário da tabela aux_SES_setor_n01"
        , setor_sigla: "Sigla do setor, originária da tabela aux_SES_setor_n01"
        , setor_nome: "Nome do setor, originário da tabela aux_SES_setor_n01"
        , inicio: "Início do setor, originário da tabela aux_SES_setor_n01"
        , emp_codigo: "Código da empresa à qual a secretaria pertence, originário da tabela aux_SES_setor_n01"
        , fim: "Data de encerramento do setor, originária da tabela aux_SES_setor_n01"
        , fim_aux: "Campo calculado para substituir o NULL dos setores que ainda estão ativos por uma data no futuro, com o objetivo de viabilizar a verificação de intervalos de início e fim"
        , setor_ordem_desc: "Campo calculado que facilita a ordenação dos setores em relação ao período de existência. Ex.: 1 indica o registro mais recente do setor. Origem na construção da tabela aux_SES_setor_n01"
        , sec_reconhecida: "Valor padrão TRUE. No processo de reconhecimento dos registros que atuam como secretarias, os registros inseridos posteriormente são marcados como FALSE"
    }    
}

    SELECT
        DISTINCT
        stox.id_aux
        , stox.codigo_secretaria AS sec_codigo
        , hsto.sigla AS sec_sigla
        , stox.setor as setor
        , stox.sigla AS setor_sigla
        , stox.nome as setor_nome
        , stox.emp_codigo
        , stox.inicio
        , stox.fim
        , stox.fim_aux
        , stox.ordem_desc as setor_ordem_desc
        , TRUE AS sec_reconhecida
    FROM
        ${ref("aux_SES_setor_n01")} stox
        LEFT JOIN ${ref("aux_SES_secretaria_n01")} hsto ON
            (
                TRIM(stox.codigo_secretaria) = TRIM(hsto.setor)
                AND stox.emp_codigo = hsto.emp_codigo
                AND stox.inicio BETWEEN hsto.inicio AND hsto.fim_aux 
                AND stox.fim_aux BETWEEN hsto.inicio AND hsto.fim_aux
            )